// GENERATED by the fixture script recorded in doc/architecture.md, then
// frozen. These are real certificates from OpenSSL 3.2.1, not certificates
// this package wrote: a parser tested only against its own encoder agrees
// with itself and with nobody else.
//
// The shapes are chosen so that a plausible bug cannot pass. In `leafPem`
// the subjectAltName is not the first extension and the URI name is neither
// the first nor the last GeneralName, so "take the first" and "take the
// last" both fail. Serials, validity windows and trust-domain paths differ
// between fixtures, so no test can pass by reading the wrong field of the
// right certificate.
//
// The private keys they were signed with were thrown away with the
// scratch directory. Nothing here can be used as an identity.

/// The trust domain's CA: CA:TRUE, pathlen 1, keyCertSign + cRLSign, URI SAN spiffe://shop-42.telepos, self-issued.
const String certificateAuthorityPem =
    '-----BEGIN CERTIFICATE-----\n'
    'MIIB5DCCAYqgAwIBAgIETR8qezAKBggqhkjOPQQDAjBEMScwJQYDVQQDDB5zaG9w\n'
    'LTQyIGluc3RhbGxhdGlvbiBhdXRob3JpdHkxGTAXBgNVBAoMEFRlbGVQT1MgZml4\n'
    'dHVyZXMwHhcNMjYwODAxMDI0OTE0WhcNMzYwNzI5MDI0OTE0WjBEMScwJQYDVQQD\n'
    'DB5zaG9wLTQyIGluc3RhbGxhdGlvbiBhdXRob3JpdHkxGTAXBgNVBAoMEFRlbGVQ\n'
    'T1MgZml4dHVyZXMwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAARZG+fmWgkKxa/r\n'
    'lW4AFtQ4MtFspvYwc5G2csYJFasqccs1HLZRIvnIlT98bPkjLK7JH5k+Jls2Dkoa\n'
    'WPbu+jKxo2owaDAdBgNVHQ4EFgQUeiBilWrTMO8CwPrObwbLlZBgslcwEgYDVR0T\n'
    'AQH/BAgwBgEB/wIBATAOBgNVHQ8BAf8EBAMCAQYwIwYDVR0RBBwwGoYYc3BpZmZl\n'
    'Oi8vc2hvcC00Mi50ZWxlcG9zMAoGCCqGSM49BAMCA0gAMEUCIHgS5cTDZx6qmqyI\n'
    'MWvu1u8MXutIQVvHr9F4qhJATRPOAiEAyzbeOyhk5ZQlmXPf5ladlAMgXL/eq8d4\n'
    'zYrH3dgWyk4=\n'
    '-----END CERTIFICATE-----\n';

/// A well-formed X.509-SVID leaf. SAN order: DNS, IP, URI, DNS. Extension order: SKI, basicConstraints, keyUsage, EKU, subjectAltName.
const String leafPem =
    '-----BEGIN CERTIFICATE-----\n'
    'MIICMTCCAdegAwIBAgIIChssPU5fYHEwCgYIKoZIzj0EAwIwRDEnMCUGA1UEAwwe\n'
    'c2hvcC00MiBpbnN0YWxsYXRpb24gYXV0aG9yaXR5MRkwFwYDVQQKDBBUZWxlUE9T\n'
    'IGZpeHR1cmVzMB4XDTI2MDgwMTAyNDkxNFoXDTI2MDgwMjAyNDkxNFowEjEQMA4G\n'
    'A1UEAwwHdGlsbC0xNzBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABG3+2EHuNc2R\n'
    'VUUjcCypVTNXWscx054RYy9okZYkefPs4B2wGCTO7IJd0dge9GgOWpfIRIFKb2yZ\n'
    'sFaRXI+vJyKjgeQwgeEwHQYDVR0OBBYEFKgORBNNTbX0JLpXRNGQq1z7AfTUMAwG\n'
    'A1UdEwEB/wQCMAAwDgYDVR0PAQH/BAQDAgWgMB0GA1UdJQQWMBQGCCsGAQUFBwMC\n'
    'BggrBgEFBQcDATBiBgNVHREEWzBZghV0aWxsLTE3LnNob3AtNDIubG9jYWyHBAoU\n'
    'HiiGK3NwaWZmZTovL3Nob3AtNDIudGVsZXBvcy90aWxsLzE3L3Rlcm1pbmFsLzOC\n'
    'DXRpbGwtMTcubG9jYWwwHwYDVR0jBBgwFoAUeiBilWrTMO8CwPrObwbLlZBgslcw\n'
    'CgYIKoZIzj0EAwIDSAAwRQIgVnnLzjHcabQwL5RZRAVTVzQo39yxUF5jrZ/4ZW5j\n'
    'cSECIQCJY0OzDh8CMJtxzaqWD1fDVOeY4PvUnfW4ijiDRFpUqg==\n'
    '-----END CERTIFICATE-----\n';

/// Two URI SANs, which the X509-SVID document forbids.
const String twoUriSansPem =
    '-----BEGIN CERTIFICATE-----\n'
    'MIIB9zCCAZygAwIBAgIBETAKBggqhkjOPQQDAjBEMScwJQYDVQQDDB5zaG9wLTQy\n'
    'IGluc3RhbGxhdGlvbiBhdXRob3JpdHkxGTAXBgNVBAoMEFRlbGVQT1MgZml4dHVy\n'
    'ZXMwHhcNMjYwODAxMDI0OTE1WhcNMjYwODAyMDI0OTE1WjASMRAwDgYDVQQDDAd0\n'
    'aWxsLTE3MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEbf7YQe41zZFVRSNwLKlV\n'
    'M1daxzHTnhFjL2iRliR58+zgHbAYJM7sgl3R2B70aA5al8hEgUpvbJmwVpFcj68n\n'
    'IqOBsDCBrTAMBgNVHRMBAf8EAjAAMA4GA1UdDwEB/wQEAwIHgDBNBgNVHREERjBE\n'
    'hiBzcGlmZmU6Ly9zaG9wLTQyLnRlbGVwb3MvdGlsbC8xN4Ygc3BpZmZlOi8vc2hv\n'
    'cC00Mi50ZWxlcG9zL3RpbGwvMTgwHQYDVR0OBBYEFKgORBNNTbX0JLpXRNGQq1z7\n'
    'AfTUMB8GA1UdIwQYMBaAFHogYpVq0zDvAsD6zm8Gy5WQYLJXMAoGCCqGSM49BAMC\n'
    'A0kAMEYCIQCWNt7fB/uxVe7p9k66IEVdTj5CX+YDwffgarmIrOmexQIhAJ2OSLIe\n'
    'eQ7qCAyHid2MNHUPNY8Gv9N8TQamM6E2DKz2\n'
    '-----END CERTIFICATE-----\n';

/// A subjectAltName with DNS names only.
const String noUriSanPem =
    '-----BEGIN CERTIFICATE-----\n'
    'MIIB1zCCAX6gAwIBAgIBEjAKBggqhkjOPQQDAjBEMScwJQYDVQQDDB5zaG9wLTQy\n'
    'IGluc3RhbGxhdGlvbiBhdXRob3JpdHkxGTAXBgNVBAoMEFRlbGVQT1MgZml4dHVy\n'
    'ZXMwHhcNMjYwODAxMDI0OTE1WhcNMjYwODAyMDI0OTE1WjASMRAwDgYDVQQDDAd0\n'
    'aWxsLTE3MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEbf7YQe41zZFVRSNwLKlV\n'
    'M1daxzHTnhFjL2iRliR58+zgHbAYJM7sgl3R2B70aA5al8hEgUpvbJmwVpFcj68n\n'
    'IqOBkjCBjzAMBgNVHRMBAf8EAjAAMA4GA1UdDwEB/wQEAwIHgDAvBgNVHREEKDAm\n'
    'ghV0aWxsLTE5LnNob3AtNDIubG9jYWyCDXRpbGwtMTkubG9jYWwwHQYDVR0OBBYE\n'
    'FKgORBNNTbX0JLpXRNGQq1z7AfTUMB8GA1UdIwQYMBaAFHogYpVq0zDvAsD6zm8G\n'
    'y5WQYLJXMAoGCCqGSM49BAMCA0cAMEQCIGHew7QWeAdnbIOSvKkEXpBzytomAw8D\n'
    'TaIiJQji3B20AiB1MiBboLpb3H3AiD2UCU2CyXF/5SkfD/U8cpajnrIDzw==\n'
    '-----END CERTIFICATE-----\n';

/// One URI SAN that is not a SPIFFE ID: the trust domain has uppercase in it.
const String malformedIdPem =
    '-----BEGIN CERTIFICATE-----\n'
    'MIIB0zCCAXqgAwIBAgIBEzAKBggqhkjOPQQDAjBEMScwJQYDVQQDDB5zaG9wLTQy\n'
    'IGluc3RhbGxhdGlvbiBhdXRob3JpdHkxGTAXBgNVBAoMEFRlbGVQT1MgZml4dHVy\n'
    'ZXMwHhcNMjYwODAxMDI0OTE1WhcNMjYwODAyMDI0OTE1WjASMRAwDgYDVQQDDAd0\n'
    'aWxsLTE3MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEbf7YQe41zZFVRSNwLKlV\n'
    'M1daxzHTnhFjL2iRliR58+zgHbAYJM7sgl3R2B70aA5al8hEgUpvbJmwVpFcj68n\n'
    'IqOBjjCBizAMBgNVHRMBAf8EAjAAMA4GA1UdDwEB/wQEAwIHgDArBgNVHREEJDAi\n'
    'hiBzcGlmZmU6Ly9TaG9wLTQyLlRFTEVQT1MvdGlsbC8xNzAdBgNVHQ4EFgQUqA5E\n'
    'E01NtfQkuldE0ZCrXPsB9NQwHwYDVR0jBBgwFoAUeiBilWrTMO8CwPrObwbLlZBg\n'
    'slcwCgYIKoZIzj0EAwIDRwAwRAIgGRnZMBwN5QlJ5C0ZCBqbySkogpUcZ5mifglZ\n'
    'DtO7f5MCIAihEvV0OVHvJOa4uuoWjxyI9pSCPjwa0vOgqKLm4Yr3\n'
    '-----END CERTIFICATE-----\n';

/// keyUsage without digitalSignature.
const String noDigitalSignaturePem =
    '-----BEGIN CERTIFICATE-----\n'
    'MIIB0zCCAXqgAwIBAgIBFDAKBggqhkjOPQQDAjBEMScwJQYDVQQDDB5zaG9wLTQy\n'
    'IGluc3RhbGxhdGlvbiBhdXRob3JpdHkxGTAXBgNVBAoMEFRlbGVQT1MgZml4dHVy\n'
    'ZXMwHhcNMjYwODAxMDI0OTE2WhcNMjYwODAyMDI0OTE2WjASMRAwDgYDVQQDDAd0\n'
    'aWxsLTE3MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEbf7YQe41zZFVRSNwLKlV\n'
    'M1daxzHTnhFjL2iRliR58+zgHbAYJM7sgl3R2B70aA5al8hEgUpvbJmwVpFcj68n\n'
    'IqOBjjCBizAMBgNVHRMBAf8EAjAAMA4GA1UdDwEB/wQEAwIFIDArBgNVHREEJDAi\n'
    'hiBzcGlmZmU6Ly9zaG9wLTQyLnRlbGVwb3MvdGlsbC8yMDAdBgNVHQ4EFgQUqA5E\n'
    'E01NtfQkuldE0ZCrXPsB9NQwHwYDVR0jBBgwFoAUeiBilWrTMO8CwPrObwbLlZBg\n'
    'slcwCgYIKoZIzj0EAwIDRwAwRAIgPKycWJUORG0mQ0UuIUcj7A0Yxj3BNXB3DGgA\n'
    '3vRDQbgCIDMzTwDOOpe9/c/FiRWCOH7q3vJ9S320X2TFjZxg5GdM\n'
    '-----END CERTIFICATE-----\n';

/// No keyUsage extension at all.
const String noKeyUsagePem =
    '-----BEGIN CERTIFICATE-----\n'
    'MIIBwzCCAWigAwIBAgIBFTAKBggqhkjOPQQDAjBEMScwJQYDVQQDDB5zaG9wLTQy\n'
    'IGluc3RhbGxhdGlvbiBhdXRob3JpdHkxGTAXBgNVBAoMEFRlbGVQT1MgZml4dHVy\n'
    'ZXMwHhcNMjYwODAxMDI0OTE2WhcNMjYwODAyMDI0OTE2WjASMRAwDgYDVQQDDAd0\n'
    'aWxsLTE3MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEbf7YQe41zZFVRSNwLKlV\n'
    'M1daxzHTnhFjL2iRliR58+zgHbAYJM7sgl3R2B70aA5al8hEgUpvbJmwVpFcj68n\n'
    'IqN9MHswDAYDVR0TAQH/BAIwADArBgNVHREEJDAihiBzcGlmZmU6Ly9zaG9wLTQy\n'
    'LnRlbGVwb3MvdGlsbC8yMTAdBgNVHQ4EFgQUqA5EE01NtfQkuldE0ZCrXPsB9NQw\n'
    'HwYDVR0jBBgwFoAUeiBilWrTMO8CwPrObwbLlZBgslcwCgYIKoZIzj0EAwIDSQAw\n'
    'RgIhAIt8RTcSaxoCRDaPoL9s0Vd9wfb4Vy7gXw7/CLXDmWjPAiEA3ueoQ6JMvM+9\n'
    'QpfdUwmh4HtrkFMnu1cBx4P3uAX2f5w=\n'
    '-----END CERTIFICATE-----\n';

/// notAfter in 2056, so both times are GeneralizedTime rather than UTCTime.
const String farFuturePem =
    '-----BEGIN CERTIFICATE-----\n'
    'MIIB1jCCAXygAwIBAgIBFjAKBggqhkjOPQQDAjBEMScwJQYDVQQDDB5zaG9wLTQy\n'
    'IGluc3RhbGxhdGlvbiBhdXRob3JpdHkxGTAXBgNVBAoMEFRlbGVQT1MgZml4dHVy\n'
    'ZXMwIBcNMjYwODAxMDI0OTE3WhgPMjA1NjA5MTIwMjQ5MTdaMBIxEDAOBgNVBAMM\n'
    'B3RpbGwtMTcwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAARt/thB7jXNkVVFI3As\n'
    'qVUzV1rHMdOeEWMvaJGWJHnz7OAdsBgkzuyCXdHYHvRoDlqXyESBSm9smbBWkVyP\n'
    'rycio4GOMIGLMAwGA1UdEwEB/wQCMAAwDgYDVR0PAQH/BAQDAgeAMCsGA1UdEQQk\n'
    'MCKGIHNwaWZmZTovL3Nob3AtNDIudGVsZXBvcy90aWxsLzIyMB0GA1UdDgQWBBSo\n'
    'DkQTTU219CS6V0TRkKtc+wH01DAfBgNVHSMEGDAWgBR6IGKVatMw7wLA+s5vBsuV\n'
    'kGCyVzAKBggqhkjOPQQDAgNIADBFAiEAyp9gGMI0d94f5zwkttWpQc+V8lKXyzWK\n'
    '1HhI8GqCPOsCIBFyVsTkxIvbbeBDEUtZSq6XQqG/oz6YC14+7sfCBa1O\n'
    '-----END CERTIFICATE-----\n';

/// A leaf whose URI SAN is the trust domain itself, with no path.
const String trustDomainIdPem =
    '-----BEGIN CERTIFICATE-----\n'
    'MIIBzDCCAXKgAwIBAgIBFzAKBggqhkjOPQQDAjBEMScwJQYDVQQDDB5zaG9wLTQy\n'
    'IGluc3RhbGxhdGlvbiBhdXRob3JpdHkxGTAXBgNVBAoMEFRlbGVQT1MgZml4dHVy\n'
    'ZXMwHhcNMjYwODAxMDI0OTE3WhcNMjYwODAyMDI0OTE3WjASMRAwDgYDVQQDDAd0\n'
    'aWxsLTE3MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEbf7YQe41zZFVRSNwLKlV\n'
    'M1daxzHTnhFjL2iRliR58+zgHbAYJM7sgl3R2B70aA5al8hEgUpvbJmwVpFcj68n\n'
    'IqOBhjCBgzAMBgNVHRMBAf8EAjAAMA4GA1UdDwEB/wQEAwIHgDAjBgNVHREEHDAa\n'
    'hhhzcGlmZmU6Ly9zaG9wLTQyLnRlbGVwb3MwHQYDVR0OBBYEFKgORBNNTbX0JLpX\n'
    'RNGQq1z7AfTUMB8GA1UdIwQYMBaAFHogYpVq0zDvAsD6zm8Gy5WQYLJXMAoGCCqG\n'
    'SM49BAMCA0gAMEUCIQC5AusoZBb4tnzFwyfJPxe7sdMPHV41IxzLc0TzL8OlGQIg\n'
    'c7hvGSQC34n3ahGfm02quT2obLpU8w7fTnRYWiptt2E=\n'
    '-----END CERTIFICATE-----\n';

/// CA:FALSE and keyCertSign together: a leaf that can sign certificates.
const String leafThatSignsPem =
    '-----BEGIN CERTIFICATE-----\n'
    'MIIB0zCCAXqgAwIBAgIBGDAKBggqhkjOPQQDAjBEMScwJQYDVQQDDB5zaG9wLTQy\n'
    'IGluc3RhbGxhdGlvbiBhdXRob3JpdHkxGTAXBgNVBAoMEFRlbGVQT1MgZml4dHVy\n'
    'ZXMwHhcNMjYwODAxMDI0OTE4WhcNMjYwODAyMDI0OTE4WjASMRAwDgYDVQQDDAd0\n'
    'aWxsLTE3MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEbf7YQe41zZFVRSNwLKlV\n'
    'M1daxzHTnhFjL2iRliR58+zgHbAYJM7sgl3R2B70aA5al8hEgUpvbJmwVpFcj68n\n'
    'IqOBjjCBizAMBgNVHRMBAf8EAjAAMA4GA1UdDwEB/wQEAwIChDArBgNVHREEJDAi\n'
    'hiBzcGlmZmU6Ly9zaG9wLTQyLnRlbGVwb3MvdGlsbC8yMzAdBgNVHQ4EFgQUqA5E\n'
    'E01NtfQkuldE0ZCrXPsB9NQwHwYDVR0jBBgwFoAUeiBilWrTMO8CwPrObwbLlZBg\n'
    'slcwCgYIKoZIzj0EAwIDRwAwRAIgFCy2VOK4rKI/RpG0tXe7pwYs3vKkWQ0WMV62\n'
    'DygDlcgCICZS4lFUZJyLToeBrXkkk3ZYixmzVSb/z/7wR+qabFr6\n'
    '-----END CERTIFICATE-----\n';
